"""empty message

Revision ID: 4f296b72bdb0
Revises: 5a22de823a1b
Create Date: 2024-02-19 01:00:35.707597

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f296b72bdb0"
down_revision: Union[str, None] = "5a22de823a1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "test_new")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("test_new", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
