name: Build and Deploy Code

on:
  push:
    branches:
      - main

jobs:
  Setup: 
    env:
      DB_HOST: localhost
      DB: Post-DB
      TEST_DB: Action-Post-DB
      DB_USER: postgres
      DB_PASSWORD: sd34EgRiv
      SECRET_KEY: gtydcdeg38920304GHUJN4567b99FEgRSD567
      JWT_ALGORITHM: HS256
      JWT_EXPIRATION_TIME_IN_MINUTE: 30
    runs-on: ubuntu-latest
    steps:
      - name: Check Ubuntu
        run: echo "Hello Earth from Ubuntu!"
      - name: Pull the code
        uses: actions/checkout@v4
      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -v -s --disable-warnings -x
