name: Build and Deploy Code

on:
  push:
    branches:
      - main

jobs:
  Setup: 
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{secrets.localhost}}
      DB: ${{secrets.Post-DB}}
      TEST_DB: ${{secrets.Action-Post-DB}}
      DB_USER: ${{secrets.secrets.DB_USER}}
      DB_PASSWORD: ${{secrets.secrets.DB_PASSWORD}}
      SECRET_KEY: ${{secrets.secrets.SECRET_KEY}}
      JWT_ALGORITHM: ${{secrets.HS256}}
      JWT_EXPIRATION_TIME_IN_MINUTE: ${{secrets.30}}
    steps:
      - name: Check Ubuntu
        run: echo "Hello Earth from Ubuntu!"
      - name: Pull the code
        uses: actions/checkout@v4
      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -v -s --disable-warnings -x
