name: Build and Deploy Code

on:
  push:
    branches:
      - main

jobs:
  Setup: 
    runs-on: ubuntu-latest
    steps:
      - name: Check Ubuntu
        run: echo "Hello Earth from Ubuntu!"
      - name: Pull the code
        uses: actions/checkout@v4
      - name: Install Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install Dependencies
        run: pip install -r requirements.txt
